name: Test master

on:
  push:
    branches:
    - master

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make build/test
    - name: Test
      run: make check
